### ISSUE TITLE
warming_hut.jar fails to launch

### ISSUE THREAD

**Issue by dldf** [423s24/Group_1#1]
Tried downloading from the releases page (https://github.com/423s24/Group_1/releases), and directly from the repo. Got a warning message on the first attempt, and simply no response to opening after that (using JavaLauncher.app). The HelloWorld demo (Project_Files.jar) does launch.

**Comment by alex-maliziola** [comment]
That's odd; we actually downloaded the warming_hut file from the releases page for our presentation on Friday (because I didn't bring my laptop and was the one who created the file) and it worked fine. I've middling experience with the ins and outs of java, but maybe it's got something to do with your OS? You're running macOS if I recall, and that's the only variable I can think of. I'll test it on some other computers and see how it runs.

**Comment by dldf** [comment]
Hi Alex,

Yes, it’s a Mac. I’ll try it again with you guys in class, either tomorrow or Wednesday.

Thanks,
Dan

From: alex-maliziola ***@***.***>
Date: Sunday, February 25, 2024 at 2:40 PM
To: 423s24/Group_1 ***@***.***>
Cc: DeFrance, Daniel ***@***.***>, Author ***@***.***>
Subject: Re: [423s24/Group_1] warming_hut.jar fails to launch (Issue #1)

**External Sender**

That's odd; we actually downloaded the warming_hut file from the releases page for our presentation on Friday (because I didn't bring my laptop and was the one who created the file) and it worked fine. I've middling experience with the ins and outs of java, but maybe it's got something to do with your OS? You're running macOS if I recall, and that's the only variable I can think of. I'll test it on some other computers and see how it runs.

**Comment by beau101023** [comment]
I've been able to replicate this issue on my home Windows 10 machine. warming_hut.jar fails to launch but Project_Files.jar does launch. Definitely worth investigating.

**Comment by beau101023** [comment]
Updating Java to the latest version resolved the issue for me. Project_Files.jar now functioning properly.

**Comment by SejongKadonk** [comment]
We have decided as a development team that for the time being our application will not support Mac as stated in the project documentation. While we have found that some Macs have been able to run our software during user testing, we have not been able to get to the root and answer the question of why some Macs could run the application and others could not. 

As we are only supporting Windows moving forward this issue is considered closed.
